# Generated by Django 4.2.6 on 2023-11-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.FileField(upload_to='flags', verbose_name='Image')),
                ('capital', models.CharField(max_length=50, verbose_name='Capital')),
            ],
        ),
    ]
