# Generated by Django 4.2.6 on 2023-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeElemani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deger', models.IntegerField()),
            ],
        ),
    ]
