# Generated by Django 4.2.6 on 2023-11-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0002_listeelemani'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagmodel',
            name='lastNumber',
            field=models.IntegerField(null=True, verbose_name='Last'),
        ),
    ]
