# Generated by Django 4.2.6 on 2023-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0003_flagmodel_lastnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastNumber', models.IntegerField(null=True, verbose_name='Last')),
            ],
        ),
        migrations.RemoveField(
            model_name='flagmodel',
            name='lastNumber',
        ),
    ]
