# Generated by Django 4.2.6 on 2023-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0004_lastnumber_remove_flagmodel_lastnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagmodel',
            name='_id',
            field=models.IntegerField(null=True, verbose_name='id'),
        ),
    ]
