# Generated by Django 4.2.6 on 2023-11-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0005_flagmodel__id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastNumber',
        ),
        migrations.DeleteModel(
            name='ListeElemani',
        ),
    ]
