# Generated by Django 4.2.6 on 2023-11-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0008_totalrecords_records'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalRecords',
        ),
    ]
