# Generated by Django 4.2.6 on 2023-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlagApp', '0011_records_createdat_records1_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='records1',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='createdAt'),
        ),
    ]
