# Generated by Django 4.2.6 on 2023-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_customuser_userlastnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeElemaniUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userListeElemaniMany', models.IntegerField(null=True, verbose_name='Many')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userListeElemani',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userListeElemani',
            field=models.ManyToManyField(to='UserApp.listeelemaniuser', verbose_name='User Liste elemanı'),
        ),
    ]
