# Generated by Django 4.2.6 on 2023-11-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_customuser_gamepoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gamePoint',
            field=models.IntegerField(blank=True, default=0, verbose_name='Game Point'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pointTotal',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Point'),
        ),
    ]
