# Generated by Django 4.2.6 on 2023-11-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_customuser_gamepoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeElemaniUser1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userListeElemaniMany', models.IntegerField(null=True, verbose_name='Many')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='userListeElemani1',
            field=models.ManyToManyField(to='UserApp.listeelemaniuser1', verbose_name='User Liste elemanı'),
        ),
    ]
