# Generated by Django 4.2.6 on 2023-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_listeelemanimistake_customuser_mistakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mistakes',
            field=models.ManyToManyField(null=True, to='UserApp.listeelemanimistake', verbose_name='Mistakes'),
        ),
    ]
