# Generated by Django 4.2.6 on 2023-11-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_alter_customuser_mistakes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mistakes',
        ),
    ]
