# Generated by Django 4.2.6 on 2023-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_remove_customuser_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstStep',
            field=models.BooleanField(default=False, verbose_name='first'),
        ),
    ]
