# Generated by Django 4.2.6 on 2023-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_customuser_firststep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstStep1',
            field=models.BooleanField(default=False, verbose_name='first'),
        ),
    ]
